# This is a basic workflow to help you get started with Actions

name: Regression Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests_linux:
    strategy:
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Making virtual environment, linting
        run: |
          make testenv
      - name: Downloading test data
        run: |
          make get_test_data
      - name: Running tests
        run: |
          source .venv/bin/activate
          coverage run --source=jwave -m pytest -vs ./tests/regression_tests
          coverage xml
          coverage html
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          name: codecov-umbrella

    # TODO: Add tests for Windows and macOS
